### ISSUE TITLE
Remove logger as an attribute of IssuePack

### ISSUE THREAD

**Issue by cmbirk** [GovReady/Issue-Packs#13]
Make it a var instead that can be modified via the constructor.  It's causing too many scoping problems.

**Comment by gregelin** [comment]
To where is the log written?

Can a user navigate to a log page and see her history?

**Comment by cmbirk** [comment]
The log is written to the console or the terminal, depending on how the library is used.

**Comment by cmbirk** [comment]
This is fixed in b66284d
