### ISSUE TITLE
Storing record of installed packs.

### ISSUE THREAD

**Issue by gregelin** [GovReady/Issue-Packs#16]
For the user experience to feel complete, we are going to have to eventually track what packs where previously installed to a repo. We should discuss simplest way to initially do this.

**Comment by cmbirk** [comment]
Because we're making the issue packs pretty flexible, it would be tough to try and pull this information from the repo.  I think the easiest method would be to create user accounts and a record of each time a issue pack is synced and where it was synced to.

**Comment by gregelin** [comment]
I agree, we would need user accounts and keep a record within issue packs.

But aren't we effectively creating a user account when user is authenticated? Can't we just keep a history for each ID authenticated? Or is there more we need to do?

**Comment by gregelin** [comment]
Not that keeping record of issues synch'ed is in the "best" category of features.

**Comment by cmbirk** [comment]
That's all we would need to do.  I just need to set up the DB on the production server to store that, as right now it's a light front-end only site.

**Comment by cmbirk** [comment]
Closing this in favor of https://github.com/GovReady/Issue-Packs-Site/issues/26
