### ISSUE TITLE
Can uploaded issues be made public for other users?

### ISSUE THREAD

**Issue by gregelin** [GovReady/Issue-Packs#18]
For us to discuss...
- When a user uploads an issue pack, do that issue pack remain private to that user? 
- Or are uploaded issue packs available to all users? 
- Can a pack be made public and or private? 
- How will a person search and find community issue packs when we get a lot?

**Comment by cmbirk** [comment]
I'll need to set up a table to store the packs, but they should probably stay private on initial upload.  The user can then make them public if they choose.  A simple search of the packs table will let people find public uploaded packs.  We should also track how many times an issue pack has been used and allow users to 'favorite' certain packs, similar to the way the [npm registry](https://www.npmjs.com/) works.

**Comment by gregelin** [comment]
I agree with above.

**Comment by cmbirk** [comment]
Closing this in favor of https://github.com/GovReady/Issue-Packs-Site/issues/24
