### ISSUE TITLE
Dealing with conflicts

### ISSUE THREAD

**Issue by cmbirk** [GovReady/Issue-Packs#5]
In the case that a milestone with the given title already exists, our options ( as I see them at the moment ) are:
-  Exit the script
-  Ask the user if they want to delete the milestone and re-create
-  Attempt to sync the issue pack with the given milestone
  - Look through existing issues & only create new ones from the pack that don't already exist
    - Including closed issues
    - Matched by title

I'm going to work at this in the order above.  I do think it's necessary to get to the third option, and here's a use case for it:
1.  A team installs an issue pack
2.  Work begins on some or all of the issues ( including issue comments )
3.  The issue pack is updated

**Comment by cmbirk** [comment]
Right now if the milestone exists, it requests all milestones, iterates until it finds one with the given title, and uses that milestone number.  This is probably good enough for this stage.

**Comment by gregelin** [comment]
Yes, finding an existing milestone and using it the right solution. This will allow additional issues to be added to an existing milestone, and eventually enabling user to choose which milestone to add issues.
