### ISSUE TITLE
Credentials YAML file

### ISSUE THREAD

**Issue by cmbirk** [GovReady/Issue-Packs#7]
This should really load a credentials YAML file.  That would also allow us to later add options of importing to other project management suites such as Jira or Basecamp.  Something like

`usage: issue-pack creds.yml pack1.yml [pack2.yml] [pack3.yml] ...`

where creds.yml contains

```
- Github
  - username: 'user'
  - password: 'password'
  - repo: 'account/repo'
- Jira
...
```

obviously right now only covering Github.

**Comment by cmbirk** [comment]
I'm pushing this back to milestone 2

**Comment by gregelin** [comment]
Wouldn't be even better if credential variables were loadable as environmental variables?
